  const hashDict = {
    DestinyActivityDefinition: "activityHash",
    DestinyActivityTypeDefinition: "activityTypeHash",
    DestinyClassDefinition: "classHash",
    DestinyGenderDefinition: "genderHash",
    DestinyInventoryBucketDefinition: "bucketHash",
    DestinyInventoryItemDefinition: "itemHash",
    DestinyProgressionDefinition: "progressionHash",
    DestinyRaceDefinition: "raceHash",
    DestinyTalentGridDefinition: "gridHash",
    DestinyUnlockFlagDefinition: "flagHash",
    DestinyHistoricalStatsDefinition: "statId",
    DestinyDirectorBookDefinition: "bookHash",
    DestinyStatDefinition: "statHash",
    DestinySandboxPerkDefinition: "perkHash",
    DestinyDestinationDefinition: "destinationHash",
    DestinyPlaceDefinition: "placeHash",
    DestinyActivityBundleDefinition: "bundleHash",
    DestinyStatGroupDefinition: "statGroupHash",
    DestinySpecialEventDefinition: "eventHash",
    DestinyFactionDefinition: "factionHash",
    DestinyVendorCategoryDefinition: "categoryHash",
    DestinyEnemyRaceDefinition: "raceHash",
    DestinyScriptedSkullDefinition: "skullHash",
    DestinyGrimoireCardDefinition: "cardId",
  };

  export default hashDict;